version: '3.8'

services:
  laravel:
    user: "33:33"
    build:
      context: ./laravel-app
      dockerfile: Dockerfile
    container_name: laravel
    volumes:
      - ./laravel-app:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - postgres
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=app
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    networks:
      - app-network

  angular:
    build:
      context: ./angular-app
    container_name: angular
    ports:
      - "4200:4200"
    volumes:
      - ./angular-app:/app
    working_dir: /app
    networks:
      - app-network

  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./laravel-app:/var/www/html:ro
    depends_on:
      - laravel
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
